# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://poluoluo.me
date_format: "ordinal"
title: 破洛洛
subtitle: "愿无岁月可回头"
description: "个人博客"
keywords: pololo
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 破洛洛
organization: poluoluo
organization_url:
github_username: pololo
location: For you, a thousand times over.
email: proluoluo@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository:

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: pololo
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: pololo
    repo: blog-comments
    oauth:
        client_id: cf56963a2f2ee3451ed9
        client_secret: 89d5655391d0f4846e2e5c8f3714738a85e6190d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
